/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * One mapped window, as reported by Hyprland (`hyprctl clients`).
 * `address` is the stable handle to pass to the move/resize functions.
 */
export interface ClientInfo {
  address: string
  pid: number
  class: string
  title: string
  x: number
  y: number
  width: number
  height: number
}

/**
 * The pointer position in the global layout, in the same coordinates as
 * `ClientInfo`'s `x`/`y`.
 */
export interface CursorPos {
  x: number
  y: number
}

/**
 * All mapped windows. Find ours by `pid` (the Electron main process owns the
 * Wayland connection, so its `process.pid` is what Hyprland reports),
 * disambiguating multiple windows of the same process by `title`/`class`.
 */
export declare function getClients(): Array<ClientInfo>

/**
 * Where the pointer is right now (`hyprctl cursorpos`). Wayland never tells a
 * client about a pointer that isn't over it, so this is the only way to follow
 * the cursor while the overlay is click-through.
 */
export declare function getCursorPos(): CursorPos

/**
 * True when running inside a Hyprland session (the IPC env vars are set).
 * Every other export fails cleanly when this is false — call it first and
 * skip the Hyprland path on other compositors.
 */
export declare function isHyprland(): boolean

/** Moves the window to an exact global position (`movewindowpixel exact`). */
export declare function moveWindowTo(address: string, x: number, y: number): void

/** Resizes the window to an exact size (`resizewindowpixel exact`). */
export declare function resizeWindowTo(address: string, width: number, height: number): void

/**
 * Runtime `hyprctl keyword <key> <value>` equivalent over the IPC socket, with
 * the compositor's reply checked (a rejected keyword throws — the hyprland
 * crate's own Keyword::set discards the reply). Covers binds too:
 * `setKeyword("bind", "CTRL ALT, R, global, web2d:recenter")`.
 */
export declare function setKeyword(key: string, value: string): void

/**
 * Applies `windowrule[<name>]:<prop> <value>` keywords — the overlay treatment
 * (pin/float/no_focus/…) for windows matching `name`. Rules set this way are
 * session-scoped; pass `value: "unset"` to clear one. Fails on the first rule
 * the compositor rejects.
 */
export declare function setWindowRules(name: string, rules: Array<WindowRule>): void

/** One dynamic windowrule property, e.g. `{ prop: "no_focus", value: "true" }`. */
export interface WindowRule {
  prop: string
  value: string
}
