/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Shortcut {
  id: string
  description: string
  preferredTrigger: string
}

/**
 * Registers `app_id` with the host portal, opens a GlobalShortcuts session, binds
 * `shortcuts`, and invokes `on_activated(id)` whenever the compositor triggers one.
 *
 * Blocks until the portal session is bound (so registration failures surface as a
 * thrown error), then keeps a background thread alive for the process lifetime
 * delivering activations. Linux/Wayland only: the portal rejects the session unless
 * `app_id` resolves to an installed `.desktop` the host registry accepts.
 */
export declare function start(appId: string, shortcuts: Array<Shortcut>, onActivated: ((err: Error | null, arg: string) => any)): void
