/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Kkkkk {
  w: number
  d: number
}
export type kkkkk = Kkkkk

export declare class Wwqe {
  awe: number
}
export type wwqe = Wwqe

export declare function eeeee(): void
