model = "zero-linux"
mirror = true
smoothing = 0.6
headGain = 1.1
headClampDeg = 90
bodyFollow = 0.4
breath = 0.4
renderFps = 120
detectFps = 50
lockHotkey = "CommandOrControl+Shift+Z"
showFps = true
showExpressions = false
hyprlandAutoBind = true
recenterHotkey = "CommandOrControl+Shift+R"

[physics]
windEnabled = false
gust = 0.05
gustHz = 0.5
springiness = 1.015

[physics.wind]
x = 0.03
y = -0.03

[eyes]
deadzone = 0
curve = 1.8
gain = 1
gazeGain = 1.1

[jaw]
deadzone = 0.0045
curve = 0.18
gain = 1

[camera]
width = 720
height = 405

[window]
x = 3829
y = 688
width = 1005
height = 883
