//! Scans the Live2D model directory for `*.exp3.json` expression files and
//! generates `src/expressions/generated.ts`, assigning each a keybind.
//!
//! Regenerate after adding/renaming expressions:
//!   rustc src/build_exp_keys.rs -o /tmp/build_exp_keys && /tmp/build_exp_keys
#![allow(dead_code)] // also compiled into the lib crate, where it's unused

use std::fmt::Write;
use std::fs;
use std::path::Path;

macro_rules! model_path {
    () => {
        "../model/ariu/"
    };
}
macro_rules! out_path {
    () => {
        "../src/expressions/generated.ts"
    };
}

const EXP_SUFFIX: &str = ".exp3.json";

/// Keys assigned to expressions in sorted order. Add more if you have >10.
const KEYS: &[&str] = &["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"];

pub fn build_keys() -> std::io::Result<()> {
    let base = std::env::current_dir()?;
    println!("Dir set to: {}", base.display());

    let mut files: Vec<String> = fs::read_dir(base.join(model_path!()))?
        .filter_map(std::result::Result::ok)
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|name| name.ends_with(EXP_SUFFIX))
        .collect();
    files.sort();

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by src/build_exp_keys.rs — do not edit by hand.\n");
    out.push_str("// Regenerate: rustc src/build_exp_keys.rs -o /tmp/build_exp_keys && /tmp/build_exp_keys\n\n");
    out.push_str("export interface ExpressionBinding {\n");
    out.push_str("\tname: string;\n");
    out.push_str("\tfile: string;\n");
    out.push_str("\tkey: string; // keyboard shortcut to toggle this expression\n");
    out.push_str("}\n\n");
    out.push_str("export const expressions: ExpressionBinding[] = [\n");
    for (i, file) in files.iter().enumerate() {
        let name = &file[..file.len() - EXP_SUFFIX.len()];
        let key = KEYS.get(i).copied().unwrap_or("");
        // {:?} emits a valid quoted/escaped string literal for these ASCII names
        let _ = writeln!(out, r"{{ name: {name:?}, file: {file:?}, key: {key:?} }},");
    }
    out.push_str("];\n");

    if let Some(dir) = Path::new(&base.join(out_path!())).parent() {
        fs::create_dir_all(dir)?;
    }
    std::io::Write::write_all(&mut fs::File::create(out_path!())?, out.as_bytes())?;
    println!("wrote {} expressions -> {}", files.len(), out_path!());
    Ok(())
}

#[test]
fn test() {
    build_keys().unwrap();
}
